name: improfweb
services:
  improf_frontend:
    container_name: improf_frontend
    build:
      context: ./frontend
    ports:
      - "3223:5173"
    restart: always
  improf_backend:
    container_name: improf_backend
    build:
      context: ./backend
    ports:
      - "3422:3000"
    restart: always
